/*
# [Operation] Create `events` and `announcements` tables

This script creates two new tables, `events` and `announcements`, to store content generated by admins. It also configures Row Level Security (RLS) to control access.

## Query Description:
This is a non-destructive operation that adds new tables and policies. It will not affect any existing data. The tables are designed to store details about club events and announcements. RLS policies are applied to ensure only admin users can add or modify content, while all logged-in users can view it.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true (Can be reversed by dropping the tables and policies)

## Structure Details:
- **New Table: `events`**
  - Columns: `id`, `created_at`, `title`, `description`, `event_date`, `venue`, `club_id`, `created_by`
- **New Table: `announcements`**
  - Columns: `id`, `created_at`, `title`, `description`, `club_id`, `created_by`

## Security Implications:
- RLS Status: Enabled on both new tables.
- Policy Changes: Yes, new policies are created.
  - `events`:
    - Admins can perform all actions (INSERT, SELECT, UPDATE, DELETE).
    - All authenticated users can view (SELECT).
  - `announcements`:
    - Admins can perform all actions (INSERT, SELECT, UPDATE, DELETE).
    - All authenticated users can view (SELECT).
- Auth Requirements: A user's role is checked via the `profiles` table.

## Performance Impact:
- Indexes: Primary key indexes are automatically created. No other indexes are added at this time.
- Triggers: None.
- Estimated Impact: Low. This change adds new tables and will not impact the performance of existing queries.
*/

-- 1. Create the `events` table
CREATE TABLE public.events (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    description text,
    event_date date,
    venue text,
    club_id text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);
ALTER TABLE public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);

-- 2. Create the `announcements` table
CREATE TABLE public.announcements (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    description text,
    club_id text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);
ALTER TABLE public.announcements ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);

-- 3. Enable RLS for the new tables
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for `events` table
CREATE POLICY "Allow all users to read events"
ON public.events
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admins to manage events"
ON public.events
FOR ALL
TO authenticated
USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

-- 5. Create RLS policies for `announcements` table
CREATE POLICY "Allow all users to read announcements"
ON public.announcements
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admins to manage announcements"
ON public.announcements
FOR ALL
TO authenticated
USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));
