/*
          # Create Content Tables and RLS Policies
          This script creates the 'events' and 'announcements' tables and sets up the necessary functions and Row Level Security (RLS) policies.

          ## Query Description: 
          This migration is safe to run. It defines a new function and creates two new tables. It will not affect any existing data. The RLS policies ensure that only users with the 'admin' role can create, update, or delete events and announcements, while all authenticated users can view them.
          
          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true (by dropping the tables and function)
          
          ## Structure Details:
          - Creates function: `get_user_role(uuid)`
          - Creates table: `events`
          - Creates table: `announcements`
          - Creates RLS policies for both tables.
          
          ## Security Implications:
          - RLS Status: Enabled for `events` and `announcements`.
          - Policy Changes: Yes, new policies are created.
          - Auth Requirements: Policies depend on the user's role in the `profiles` table.
          
          ## Performance Impact:
          - Indexes: Primary key indexes are created automatically.
          - Triggers: None.
          - Estimated Impact: Low. RLS checks will have a negligible impact on performance for this use case.
          */

-- 1. Create a function to get a user's role from their profile.
-- This function is crucial for the RLS policies to work correctly.
-- It is defined with `SECURITY DEFINER` to allow it to read the profiles table
-- even when the calling user does not have direct select permissions on it.
CREATE OR REPLACE FUNCTION public.get_user_role(user_id uuid)
RETURNS user_role AS $$
DECLARE
  user_role_result user_role;
BEGIN
  SELECT role INTO user_role_result FROM public.profiles WHERE id = user_id;
  RETURN user_role_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. Create the 'events' table
CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text,
    event_date timestamp with time zone NOT NULL,
    venue text,
    club_id text NOT NULL
);

-- 3. Create the 'announcements' table
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text NOT NULL,
    description text,
    club_id text NOT NULL
);

-- 4. Enable Row Level Security (RLS) on both tables
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies if they exist, to prevent errors on re-run
DROP POLICY IF EXISTS "Allow all authenticated users to read" ON public.events;
DROP POLICY IF EXISTS "Allow admins to insert" ON public.events;
DROP POLICY IF EXISTS "Allow admins to update and delete" ON public.events;
DROP POLICY IF EXISTS "Allow all authenticated users to read" ON public.announcements;
DROP POLICY IF EXISTS "Allow admins to insert" ON public.announcements;
DROP POLICY IF EXISTS "Allow admins to update and delete" ON public.announcements;

-- 6. Create RLS policies for the 'events' table
CREATE POLICY "Allow all authenticated users to read"
ON public.events FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admins to insert"
ON public.events FOR INSERT
TO authenticated
WITH CHECK (public.get_user_role(auth.uid()) = 'admin'::user_role);

CREATE POLICY "Allow admins to update and delete"
ON public.events FOR UPDATE, DELETE
TO authenticated
USING (public.get_user_role(auth.uid()) = 'admin'::user_role);

-- 7. Create RLS policies for the 'announcements' table
CREATE POLICY "Allow all authenticated users to read"
ON public.announcements FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow admins to insert"
ON public.announcements FOR INSERT
TO authenticated
WITH CHECK (public.get_user_role(auth.uid()) = 'admin'::user_role);

CREATE POLICY "Allow admins to update and delete"
ON public.announcements FOR UPDATE, DELETE
TO authenticated
USING (public.get_user_role(auth.uid()) = 'admin'::user_role);
